config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'static_pages#home'
  get 'users/index' => "users#index"

  get 'sessions/new'

  get "home" => 'static_pages#home'

  get  "help" => 'static_pages#help'

  get  "terms" => 'static_pages#terms'

  get  "privacy" => 'static_pages#privacy'

  get 'static_pages/:params' => 'static_pages#home'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'events/calendar_month' => "events#calendar_month"

  get 'events/new' => 'events#new'

  get 'events/:id' => 'events#list_by_name', as: 'list_by_name'

  get '/events' => "users#login"

  get 'events/:params' => "users#login"

  get 'signup' => "users#new", as: :signup

  resources :events

  get '/:parms' => "users#login"

  get '/list' => 'events#list'

end

app/models/event.rb
class Event < ActiveRecord::Base

belongs_to :user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :show, :destroy]


  def calendar_month
    @events = Event.where(:user_id => current_user.id)
  end

  def list
    @user = User.find_by_id(1)
    @events = @user.events.all
  end

  def list_by_name
    # @pin = Pin.find_by_slug(params[:slug])
    @user = User.find_by_id(session[:user_id])
    puts "#{@user.id} x" * 100
    # @user = User.find_by_id(1)
    @events = @user.events.all
    render :list_by_name
    # @pin = Pin.find_by_slug(params[:slug])
    # render :show
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    #going to have to find the user here
    #this means create the login and the session
    @user = User.find(@event.user_id)
  end

  # GET /events/new
  def new
    @user = User.find_by_id(session[:user_id])
    puts "in new event" * 100
    @event = Event.new
    @event.user_id = session[:user_id]
    puts " #{@event.user_id}" * 25
  end

  # GET /events/1/edit
  def edit
    @user = User.find_by_id(session[:user_id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to list_by_name_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event, :eventdate, :notes, :user_id)
    end

    def correct_user
      @user = User.find(Event.find(params[:id]).user_id)
      redirect_to(root_url) unless current_user?(@user)
      # redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
<h4>Tracking for: <i><%= current_user.patient_name  %></i> </h4>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :eventdate, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_field :event, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <%= f.hidden_field :user_id, class: "form-control" %>

  </div>
</div>

  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/events/calendar_month.html.erb
<div class="">
	<h4>HealthTraks (beta)<br><small><i>for <%= current_user.patient_name  %></i></small></h4>
</div>

<div class="event_button">
		<%= link_to '+ New Entry', new_event_path, html_options={class: "btn btn-success"} %>
		<%= link_to 'List View', session[:user_id].to_s, html_options={class: "btn btn-info"} %>
</div>

<%= month_calendar(attribute: :eventdate, events: @events) do |date, events| %>
	<div id="calendar-date"><%= date.day%></div>

	<% events.each do |event| %>
		<div class="calendar-entry">
			<%= event.event %>
		</div>
	<% end %>
<% end %>

app/views/events/edit.html.erb
<div class="">
<h4>HealthTraks (beta)<br><small><i>View, edit, or delete this entry</i></small></h4>
</div>

<%= link_to ' Cancel and go back', list_by_name_path, html_options = { class: "btn btn-warning"} %>
<%= link_to ' Delete this entry',  @event, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>

<%= render 'form' %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
	<h1>HealthTraks<br><small><i>for River Joanie</i></small></h1>

</div>

<div class="event_button">
		<%= link_to '+ New Entry', new_event_path, html_options={class: "btn btn-success"} %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Event</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.eventdate.strftime('%a %m/%d/%Y'), event %></td>
		<td><%= event.event %></td>
        <td><%= event.notes.truncate(30) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/list.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
	<h1>HealthTraks<br><small><i>for <%= @user.patient_name  %></i></small></h1>

</div>

<div class="event_button">
		<%= link_to '+ New Entry', new_event_path, html_options={class: "btn btn-success"} %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Event</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.eventdate.strftime('%a %m/%d/%Y'), event %></td>
    <td><%= event.event %></td>
        <td><%= event.notes.truncate(30) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/list_by_name.html.erb
<p id="notice"><%= notice %></p>

<div class="">
	<h4>HealthTraks (beta)<br><small><i>for <%= current_user.patient_name  %></i></small></h4>
</div>

<div class="event_button">
		<%= link_to '+ New Entry', new_event_path, html_options={class: "btn btn-success"} %>
		<%= link_to 'Calendar View', events_calendar_month_path, html_options={class: "btn btn-info"} %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Entry</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.eventdate.strftime('%a %m/%d/%Y'), edit_event_path(event.id) %></td>
    <td><%= event.event %></td>
        <td><%= event.notes.truncate(40) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<div class="">
<h4>HealthTraks (beta)<br><small><i>Create New Entry</i></small></h4>
</div>

<%= link_to ' Cancel and go back', session[:user_id].to_s, html_options = { class: "btn btn-warning"} %>



<%= render 'form' %>

app/views/events/show.html.erb
<h1>HealthTraks<br><small><i>for <%= @user.patient_name %></i></small></h1>

<hr>

<div class="menu-bar">
	<%= link_to ' Edit', edit_event_path(@event), html_options = { class: "btn btn-success" } %>
	<%= link_to ' Back to List', events_path, html_options = { class: "btn btn-success"} %>
	<%= link_to ' Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.eventdate.strftime('%a %m/%d/%Y') %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @event.event %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @event.notes %>
</p>

app/views/events/working_calendar_month.html.erb
<div class="jumbotron">
	<h1>HealthTraks (beta)<br><small><i>Calendar</i></small></h1>
</div>

<div class="event_button">
		<%= link_to '+ New Entry', new_event_path, html_options={class: "btn btn-success"} %>
		<%= link_to 'List View', session[:user_id].to_s, html_options={class: "btn btn-info"} %>
</div>

<%= month_calendar(attribute: :eventdate, events: @events) do |date, events| %>
	<%= date %>

	<% events.each do |event| %>
		<div class="calendar-entry">
			<%= event.event %>
		</div>
	<% end %>
<% end %>