config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root  'static_pages#home'
  get 'users/index' => "users#index"

  get 'sessions/new'

  get "home" => 'static_pages#home'

  get  "help" => 'static_pages#help'

  get  "terms" => 'static_pages#terms'

  get  "privacy" => 'static_pages#privacy'

  get 'static_pages/:params' => 'static_pages#home'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'events/calendar_month' => "events#calendar_month"

  get 'events/new' => 'events#new'

  get 'events/:id' => 'events#list_by_name', as: 'list_by_name'

  get '/events' => "users#login"

  get 'events/:params' => "users#login"

  get 'signup' => "users#new", as: :signup

  resources :events

  get '/:parms' => "users#login"

  get '/list' => 'events#list'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <hr>
  <p style=color:#778899;><i>Healthtraks</i> &copy; 2016 by ChapApptive, LLC. All rights reserved. <%= link_to ' Terms of Service', '/terms', html_options = { target: "_blank"} %> and <%= link_to ' Privacy Policy', '/privacy', html_options = { target: "_blank"} %>.</p>
</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in?%>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>

</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Healthtrak</title>
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/header' %>
	<div class="container">

      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

		<%= yield %>




		<hr>
		<p style=color:#778899;><i>Healthtraks</i> &copy; 2016 by ChapApptive, LLC. All rights reserved. <%= link_to ' Terms of Service', '/terms', html_options = { target: "_blank"} %> and <%= link_to ' Privacy Policy', '/privacy', html_options = { target: "_blank"} %>.</p>



    <%= debug(params) if Rails.env.development? %>

	</div>

</body>
</html>